# encoding: utf-8

defaults: &defaults
  project_name: 'Quana'

  api_page_size: 20
  autocomplete_results_count: 20

  # SMS Client
  sms_client_type: 'twilio'
  sms_client_sender_id: '+12056062179'

  # Code Validation
  code_length: 4
  max_tries_count: 3
  max_codes_per_user: 3

  qa_code:  '1234'  
  qa_phone: '+97299999999'

  default_country_code: 'IL'

test:
  <<: *defaults

  server_domain: 'localhost:3000'

  # AWS S3
  aws_s3_region:
  aws_s3_bucket:

development:
  <<: *defaults

  server_domain: 'localhost:3000'

  # AWS S3
  aws_s3_region: eu-west-1
  aws_s3_bucket: quana

staging:
  <<: *defaults

  server_domain: 'quana-server-staging.herokuapp.com'

  # AWS S3
  aws_s3_region:
  aws_s3_bucket:

production:
  <<: *defaults

  server_domain: 'quana-server-production.herokuapp.com'

  # AWS S3
  aws_s3_region:
  aws_s3_bucket: 