# General
secret_key_base: 

# Devise 2FA
opt_encryption_key: 

# SMS Client
sms_client_username:
sms_client_password:

# AWS S3
aws_access_key_id: 
aws_secret_access_key: 

# Push Notifications
fcm_key: