default: &default
  database: quana_dev
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: postgres
  username: postgres
  pool: 5

# list all supported environments here, to allow editing of the corresponding credentials file in dev mode
# (otherwise, an exception is thrown, and this file is overridden by Heroku anyway)
test:
  <<: *default
  database: quana_test
  host: postgres
  username: postgres
  password: postgres

development: 
  <<: *default

staging:
  <<: *default

production:
  <<: *default
