name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@master
    - name: Install libraries
      run: |
        apt-get update
        apt-get -yqq install libpq-dev
        apt-get -yqq install nodejs
    - name: Install gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Migrate and Test
      env:
        DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails test
    container:
      image: ruby:2.6.4
